/**
 * Defines the contract for email provider adapters.
 * Implementations must remain portable across providers (Resend, SendGrid, etc.)
 * following the Adapter Pattern defined in Architecture §16.
 */

/** Data required to dispatch the lead confirmation email */
export interface EmailPayload {
    /** Lead's email address (recipient) */
    to: string;

    /** Lead's first name for personalized greeting */
    leadFirstName: string;

    /** Lead's full name for pre-filling Calendly */
    leadFullName: string;

    /** PDF content as Base64-encoded string (with or without data URI prefix) */
    pdfBase64: string;

    /** Filename for the PDF attachment (e.g. Plan_Financiero_John_Doe.pdf) */
    pdfFilename: string;

    /** Pre-filled Calendly booking URL with lead's name and email */
    bookingUrl: string;

    /** Language for email copy (determines ES/EN subject and body text) */
    lang: 'ES' | 'EN';

    /** Pre-built HTML email body string (generated by EmailService.buildHtmlBody) */
    htmlBody: string;
}

/** Result of an email send operation */
export interface EmailResult {
    success: boolean;
    errorMessage?: string;
}

/**
 * Abstract contract for all email provider adapters.
 * Swap the implementation in app.config.ts to change providers.
 */
export abstract class IEmailProvider {
    abstract send(payload: EmailPayload): Promise<EmailResult>;
}
