# Simple workflow for deploying Angular web app to GitHub Pages
name: Deploy Angular App to GitHub Pages

on:
  # Runs on pushes targeting the default branch
  push:
    # branches: ['main', 'develop', 'feature/TS-01_Initial_Angular_Project_Structure']
    branches:
      - main
      - develop
      - feature/TS-02_Initial_Angular_Standard_Rules

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: write
  # contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: 'pages'
  cancel-in-progress: false

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'pnpm'
          # package-manager: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Build Angular App for Production
        # run: pnpm run build:prod
        run: pnpm ng build --configuration production --base-href /financial-tracker/ --deploy-url /financial-tracker/

      # Route file renaming for index.html to 404.html for GitHub Pages routing
      - name: Rename index for routing
        run: mv dist/financial-tracker/browser/index.html dist/financial-tracker/browser/404.html

      # Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist/financial-tracker/browser
          publish_branch: gh-pages
          # clean: true

      # # Deploy to Github pages
      # - name: Deploy to GitHub Pages
      #   uses: crazy-max/ghaction-github-pages@v3.1.0
      #   with:
      #     build_dir: dist/financial-tracker/browser
      #   env:
      #     GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

# jobs:
#   # Single deploy job since we're just deploying
#   deploy:
#     environment:
#       name: github-pages
#       url: ${{ steps.deployment.outputs.page_url }}
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout
#         uses: actions/checkout@v4
#       - name: Setup Pages
#         uses: actions/configure-pages@v5
#       - name: Upload artifact
#         uses: actions/upload-pages-artifact@v3
#         with:
#           # Upload just src folder
#           path: './src'
#       - name: Deploy to GitHub Pages
#         id: deployment
#         uses: actions/deploy-pages@v4
